### ISSUE TITLE
utils.py probably missing

### ISSUE THREAD

**Issue by giulliabraga** [nollexu/LA-GMF#1]
Hello! First of all, thank you for your project, it's really helping me out through my research 🥇 

I just wanted to ask if you could include what should be your utils.py

You import it on this line: from utils import cal_metrics, setup_seed

I assume you're not doing much, just calculating some metrics and setting up a seed, but since I'm more or less trying to reproduce what you did it would spare me some time if you could make that available as well.

Thanks a lot 🐣

**Comment by nollexu** [comment]
Hello, thank you for the reminder. The utils file was indeed forgotten🙃, I've uploaded it.

**Comment by giulliabraga** [comment]
thank you so much, it's been great help :) btw, could i chat with you via email to ask a few more questions? i think you're not the same person as the corresponding author of the paper, so i'm not sure who I should contact for code-related questions... promiss not to be a bug haha 😹

**Comment by nollexu** [comment]
nolle98xu@gmail.com
